Update build-emsdk.yml

diff --git a/.github/workflows/build-emsdk.yml b/.github/workflows/build-emsdk.yml
--- a/.github/workflows/build-emsdk.yml
+++ b/.github/workflows/build-emsdk.yml
@@ -60,7 +60,7 @@ jobs:
         echo "Estraendo l'archivio..."
         sudo tar -xvf ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE -C /opt --use-compress-program=lz4
         echo "Contenuto di /opt dopo l'estrazione:"
-        sudo ls -R /opt/python-wasm-sdk || { echo "Errore nell'accesso a /opt/python-wasm-sdk"; exit 1; }  # Stampa il contenuto della directory
+        sudo ls -R /opt/python-wasm-sdk || { echo "Errore nell'accesso a /opt/python-wasm-sdk"; exit 1; } 
 
     - name: Search for python3-wasm
       run: |
@@ -73,7 +73,7 @@ jobs:
         if [ -f "/opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm" ]; then
             chmod +x /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm  # Assicurati che sia eseguibile
             echo "Trovato python3-wasm, avvio della build..."
-            /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm p/main.py build -j$(nproc) || { echo "Build failed"; exit 1; }
+            /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm p/main.py build -j$(nproc) -v || { echo "Build failed"; exit 1; }
         else
             echo "Il file python3-wasm non esiste in /opt/python-wasm-sdk/prebuilt/emsdk"
             exit 1
