Update build-emsdk.yml

diff --git a/.github/workflows/build-emsdk.yml b/.github/workflows/build-emsdk.yml
--- a/.github/workflows/build-emsdk.yml
+++ b/.github/workflows/build-emsdk.yml
@@ -34,10 +34,13 @@ jobs:
       - name: Build WASM Game
         run: |
           echo "Starting the game build..."
-          pygbag p/main.py || echo "Build failed"  # Aggiungi un messaggio per la diagnosi
+          pygbag p/main.py || echo "Build failed"  # Log di errore per la build
+
+      - name: List directory contents after build
+        run: ls -R build  # Verifica se la directory build è stata creata
 
       - name: List build/web contents
-        run: ls -R build/web  # Verifica i file generati nella directory build/web
+        run: ls -R build/web || echo "Directory build/web does not exist"  # Verifica la directory build/web
 
       - name: Upload build artifacts
         uses: actions/upload-artifact@v4
