Update build-emsdk.yml

diff --git a/.github/workflows/build-emsdk.yml b/.github/workflows/build-emsdk.yml
--- a/.github/workflows/build-emsdk.yml
+++ b/.github/workflows/build-emsdk.yml
@@ -40,24 +40,28 @@ jobs:
         sudo apt-get install -y lz4
         pip3 install cython==3.0.10 pygame pygbag flask gunicorn
 
-    - name: Install python-wasm-sdk
+    - name: Create download directory
       run: |
         mkdir -p ${{ github.workspace }}/sdk_downloads
+        echo "Download directory created."
+
+    - name: Install python-wasm-sdk
+      run: |
         echo "Downloading SDK..."
         curl -sL --retry 5 -o ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE
         echo "Extracting SDK..."
         tar -xvf ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE -C /opt --use-compress-program=lz4 || { echo "Extraction failed"; exit 1; }
+        echo "Extraction complete."
 
     - name: List extracted files
       run: |
         echo "Contenuto di /opt/python-wasm-sdk:"
-        ls -R /opt/python-wasm-sdk
+        ls -R /opt/python-wasm-sdk || { echo "Listing failed"; exit 1; }
 
     - name: Check for python3-wasm directory
       run: |
         if [ -d "/opt/python-wasm-sdk/python3-wasm" ]; then
             echo "Trovata la directory python3-wasm."
-            # Check for the executable file inside the directory
             if [ -f "/opt/python-wasm-sdk/python3-wasm/p/main.py" ]; then
                 echo "Trovato main.py, avvio della build..."
             else
@@ -71,11 +75,16 @@ jobs:
 
     - name: Build WASM with emsdk
       run: |
+        echo "Rendere main.py eseguibile..."
         chmod +x /opt/python-wasm-sdk/python3-wasm/p/main.py
+        echo "Avviando la build..."
         /opt/python-wasm-sdk/python3-wasm/p/main.py build -j$(nproc) || { echo "Build failed"; exit 1; }
 
     - name: Clean up
-      run: rm -rf ${{ github.workspace }}/sdk_downloads
+      run: |
+        echo "Pulizia dei file scaricati..."
+        rm -rf ${{ github.workspace }}/sdk_downloads
+        echo "Pulizia completata."
 
     - name: Upload dist
       uses: actions/upload-artifact@v4
