Update build-emsdk.yml

diff --git a/.github/workflows/build-emsdk.yml b/.github/workflows/build-emsdk.yml
--- a/.github/workflows/build-emsdk.yml
+++ b/.github/workflows/build-emsdk.yml
@@ -58,14 +58,14 @@ jobs:
         echo "Downloading SDK from https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE"
         curl -sL --retry 5 -o ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE
         echo "Estraendo l'archivio..."
-        tar -xvf ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE -C /opt --use-compress-program=lz4
-        echo "Contenuto di /opt/python-wasm-sdk dopo l'estrazione:"
-        ls -R /opt/python-wasm-sdk  # Stampa il contenuto della directory
+        sudo tar -xvf ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE -C /opt --use-compress-program=lz4
+        echo "Contenuto di /opt dopo l'estrazione:"
+        sudo ls -R /opt/python-wasm-sdk || { echo "Errore nell'accesso a /opt/python-wasm-sdk"; exit 1; }  # Stampa il contenuto della directory
 
     - name: Search for python3-wasm
       run: |
         echo "Cercando il file python3-wasm all'interno di /opt/python-wasm-sdk..."
-        find /opt/python-wasm-sdk -name "python3-wasm" || { echo "Find command failed"; exit 1; }
+        sudo find /opt/python-wasm-sdk -name "python3-wasm" || { echo "Find command failed"; exit 1; }
 
     - name: Build WASM with emsdk
       run: |
