Update build-emsdk.yml

diff --git a/.github/workflows/build-emsdk.yml b/.github/workflows/build-emsdk.yml
--- a/.github/workflows/build-emsdk.yml
+++ b/.github/workflows/build-emsdk.yml
@@ -23,10 +23,6 @@ on:
       - '.github/workflows/*.yml'
       - '!.github/workflows/build-emsdk.yml'
 
-concurrency:
-  group: ${{ github.workflow }}-${{ github.ref }}-emsdk
-  cancel-in-progress: true
-
 jobs:
   build:
     runs-on: ubuntu-22.04
@@ -38,54 +34,33 @@ jobs:
     steps:
     - uses: actions/checkout@v4.2.0
 
-    - name: Check available disk space
-      run: df -h
-
     - name: Install dependencies
       run: |
-        pip3 install cython==3.0.10
-        pip3 install pygame
-        pip3 install pygbag
-        pip3 install flask
-        pip3 install gunicorn
-
-    - name: Create download directory
-      run: mkdir -p ${{ github.workspace }}/sdk_downloads
+        sudo apt-get update
+        sudo apt-get install -y lz4
+        pip3 install cython==3.0.10 pygame pygbag flask gunicorn
 
     - name: Install python-wasm-sdk
       run: |
-        sudo apt-get install -y lz4
-        echo "Downloading SDK from https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE"
+        mkdir -p ${{ github.workspace }}/sdk_downloads
+        echo "Downloading SDK..."
         curl -sL --retry 5 -o ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE https://github.com/pygame-web/python-wasm-sdk/releases/download/$SDK_VERSION/$SDK_ARCHIVE
+        echo "Extracting SDK..."
         tar -xvf ${{ github.workspace }}/sdk_downloads/$SDK_ARCHIVE -C /opt --use-compress-program=lz4
-        echo "Contenuto di /opt/python-wasm-sdk dopo l'estrazione:"
-        ls -R /opt/python-wasm-sdk  # Mostra tutto il contenuto di /opt/python-wasm-sdk
 
     - name: Build WASM with emsdk
       run: |
-        echo "Controllando il contenuto della directory /opt/python-wasm-sdk/prebuilt/emsdk..."
-        ls -al /opt/python-wasm-sdk/prebuilt/emsdk  # Mostra tutti i file e le directory, anche quelle nascoste
-
-        echo "Controllando se il file python3-wasm esiste..."
         if [ -f "/opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm" ]; then
-            echo "Trovato python3-wasm, verifico i permessi..."
-            ls -l /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm  # Mostra i permessi del file
-            chmod +x /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm  # Assicurati che il file sia eseguibile
             echo "Avviando la build WASM..."
-            /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm p/main.py build -j$(nproc) -v || { echo "Build failed"; exit 1; }
+            chmod +x /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm
+            /opt/python-wasm-sdk/prebuilt/emsdk/python3-wasm p/main.py build -j$(nproc) || { echo "Build failed"; exit 1; }
         else
-            echo "Il file python3-wasm non esiste in /opt/python-wasm-sdk/prebuilt/emsdk"
+            echo "Il file python3-wasm non esiste."
             exit 1
         fi
 
-    - name: Generate libpygame.a static binaries archive
-      run: |
-        mkdir -p dist
-        SYS_PYTHON=python3 /opt/python-wasm-sdk/prebuilt/emsdk/emscripten/emar rcs dist/libpygame.a $(find build/temp.wasm32-*/ | grep o$)
-
-    - name: Clean up after build
-      run: |
-        rm -rf ${{ github.workspace }}/sdk_downloads
+    - name: Clean up
+      run: rm -rf ${{ github.workspace }}/sdk_downloads
 
     - name: Upload dist
       uses: actions/upload-artifact@v4
